{
 "title": "daily_dashboard_for_invalid_data",
 "time": { "from": "2025-08-12T21:01:30.071Z", "to": "2025-08-13T21:01:30.071Z" },
 "panels": [
  {
   "title": "Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT strftime(current_date , '%Y-%m-%d');\r\n"
    }
   ]
  },
  {
   "title": "Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT 'Reasons of invalid data'"
    }
   ]
  },
  {
   "title": "Invalid data per sport",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT message ->> 'strSport' AS sport, COUNT(*) AS null_and_empty\r\nFROM read_parquet('/data/kafka_invalid/' || strftime(current_date , '%Y-%m-%d') || '.parquet')\r\nGROUP BY 1\r\nORDER BY null_and_empty DESC\r\nLIMIT 20\r\n"
    }
   ]
  },
  {
   "title": "All Invalid Data Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS 'number of all invalid data'\r\nFROM read_parquet(\r\n    '/data/kafka_invalid/' || strftime(current_date , '%Y-%m-%d') || '.parquet'\r\n)\r\n\r\n"
    }
   ]
  },
  {
   "title": "invlid data in every topic",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT topic, COUNT(*) AS message_count\r\nFROM read_parquet(\r\n    '/data/kafka_invalid/' || strftime(current_date, '%Y-%m-%d') || '.parquet'\r\n)\r\nGROUP BY topic\r\nORDER BY message_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "match status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT message ->> 'strStatus' AS 'Status of match', COUNT(*) AS null_values\r\nFROM read_parquet('/data/kafka_invalid/' || strftime(current_date , '%Y-%m-%d') || '.parquet')\r\nGROUP BY 1\r\nORDER BY null_values DESC\r\nLIMIT 20\r\n"
    }
   ]
  },
  {
   "title": "show all message invalid with reason",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    topic AS topic,\r\n    message ->> 'strSport' AS strSport,\r\n    message ->> 'strStatus' AS strStatus\r\nFROM read_parquet('/data/kafka_invalid/' || strftime(current_date, '%Y-%m-%d') || '.parquet')\r\nORDER BY strStatus;\r\n\r\n"
    }
   ]
  },
  {
   "title": "show all invalid data in parquet",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM read_parquet('/data/kafka_invalid/' || strftime(current_date, '%Y-%m-%d') || '.parquet')\r\nWHERE message ->> 'strStatus' IN ('FT', 'AOT', 'AP', 'NS', 'Match Cancelled', 'null_values');"
    }
   ]
  }
 ]
}